# -*- coding: utf-8 -*-
"""stock_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAfEG5VE9a8qBSgjQcigiM68ilB_dCNr
"""

!pip install -q fastapi uvicorn yfinance pandas ta xgboost requests
print("✅ All dependencies installed!")

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import yfinance as yf
import pandas as pd
from ta.momentum import RSIIndicator
from ta.trend import MACD
from xgboost import XGBClassifier
import uvicorn
from threading import Thread
import time
import requests

print("✅ All libraries imported!")

app = FastAPI(title="QuantFlip API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/predict/{ticker}")
def predict_stock(ticker: str):
    try:
        formatted_ticker = ticker.upper()
        if "." not in formatted_ticker:
            formatted_ticker = f"{formatted_ticker}.NS"

        print(f"📊 Analyzing {formatted_ticker}...")

        df = yf.download(formatted_ticker, period="2y", interval="1d", progress=False)

        if df.empty:
            return {"error": f"Invalid ticker: {formatted_ticker}", "success": False}

        if isinstance(df.columns, pd.MultiIndex):
            df.columns = df.columns.get_level_values(0)

        df['RSI'] = RSIIndicator(df['Close'], window=14).rsi()
        macd = MACD(df['Close'])
        df['MACD'] = macd.macd()
        df['MACD_Signal'] = macd.macd_signal()
        df['Return'] = df['Close'].pct_change()
        df['Target'] = (df['Close'].shift(-3) > df['Close']).astype(int)

        clean_df = df.dropna().copy()

        if len(clean_df) < 20:
            return {"error": "Insufficient data", "success": False}

        features = ['RSI', 'MACD', 'MACD_Signal', 'Return']
        X = clean_df[features]
        y = clean_df['Target']

        model = XGBClassifier(n_estimators=50, max_depth=3, learning_rate=0.05, random_state=42, verbosity=0)

        if len(X) > 10:
            model.fit(X[:-10], y[:-10])
        else:
            model.fit(X, y)

        latest_data = X.iloc[[-1]]
        prob_up = float(model.predict_proba(latest_data)[0][1])
        current_price = float(df['Close'].iloc[-1])

        if prob_up >= 0.60:
            recommendation = "CALCULATED BUY (Favorable Odds)"
            signal_color = "🟢 GREEN"
        elif prob_up <= 0.40:
            recommendation = "HIGH RISK / AVOID"
            signal_color = "🔴 RED"
        else:
            recommendation = "50/50 COINFLIP"
            signal_color = "🟡 YELLOW"

        return {
            "ticker": formatted_ticker,
            "current_price_inr": round(current_price, 2),
            "upside_probability_pct": round(prob_up * 100, 1),
            "recommendation": recommendation,
            "signal_color": signal_color,
            "success": True
        }

    except Exception as e:
        return {"error": str(e), "success": False}

@app.get("/health")
def health_check():
    return {"status": "API running ✅"}

print("✅ FastAPI app created!")

def run_server():
    uvicorn.run(app, host="127.0.0.1", port=8000, log_level="warning")

server_thread = Thread(target=run_server, daemon=True)
server_thread.start()

print("⏳ Starting backend server...")
time.sleep(4)
print("✅ Backend running!\n")

def analyze_stock(ticker):
    """Analyze a stock"""
    try:
        response = requests.get(f"http://127.0.0.1:8000/predict/{ticker}", timeout=60)

        if response.status_code == 200:
            result = response.json()

            if result.get("success") == False:
                print(f"❌ Error: {result.get('error')}\n")
                return

            print("\n" + "="*60)
            print(f"📊 {result['ticker']}")
            print("="*60)
            print(f"💰 Price: ₹{result['current_price_inr']}")
            print(f"📈 Upside: {result['upside_probability_pct']}%")
            print(f"🎯 Signal: {result['signal_color']}")
            print(f"🎲 Recommendation: {result['recommendation']}")
            print("="*60 + "\n")
        else:
            print(f"API Error: {response.status_code}")

    except Exception as e:
        print(f"❌ Error: {str(e)}")

print("✅ Ready to analyze!\n")

analyze_stock("INFY")